version: 2

sources:
  - name: raw
    schema: gz_raw_data
    tables:
      - name: sales
        identifier: raw_gz_sales
        tests:
          - unique:
              column_name: "(orders_id || '-' || pdt_id)"
        freshness:
          warn_after: { count: 90, period: day }
        loaded_at_field: "CAST(date_date AS TIMESTAMP)"

      - name: product
        identifier: raw_gz_product
        description: primry key of product
        columns:
          - name: products_id
            tests:
              - unique
              - not_null

      - name: ship
        identifier: raw_gz_ship
        columns:
          - name: orders_id
            tests:
              - unique
              - not_null
